# Generated by Django 5.1.6 on 2025-07-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GarageProfile',
        ),
    ]
