# Generated by Django 5.1.6 on 2025-07-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic Maintenance'), ('performance', 'Performance Upgrade'), ('tuning', 'Custom Tuning'), ('aesthetic', 'Aesthetic Mod')], default='basic', max_length=20),
        ),
    ]
