# Generated by Django 5.1.6 on 2025-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0004_servicetype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='category',
            field=models.CharField(choices=[('Basic', 'Basic Maintenance'), ('Performance', 'Performance Upgrade'), ('Tuning', 'Custom Tuning'), ('Aesthetic', 'Aesthetic Mod')], default='basic', max_length=20),
        ),
    ]
