# Generated by Django 5.1.6 on 2025-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0005_car_image_alter_servicetype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
