# Generated by Django 5.1.6 on 2025-07-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0006_car_horsepower'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='upgrades',
            field=models.TextField(blank=True),
        ),
    ]
