# Generated by Django 5.1.6 on 2025-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0007_car_upgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='hp_gain',
            field=models.PositiveIntegerField(default=0, help_text='Horsepower gain from this service'),
        ),
    ]
